spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: postgres
    username: postgres
    url: jdbc:postgresql://127.0.0.1:5432/taotao
    driver-class-name: org.postgresql.Driver
    dbcp2:
      max-wait-millis: 3000
      initial-size: 10
      max-idle: 5
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    host: 127.0.0.1
    port: 7001
  application:
    name: taotaomall-consumer
  dubbo:
    server: true
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: zookeeper://127.0.0.1:2181
    application:
      name: ${spring.application.name}
    consumer:
      check: false
    reference:
     loadbalance: roundrobin
server:
  servlet:
    context-path: /taotaomall/consumer
  port: 8081

