server:
  port: 8083
  servlet:
    context-path: /taotaomall/sso
spring:
  application:
    name: sso
  dubbo:
    server: true
    protocol:
      name: dubbo
      port: 20881
    registry:
      address: zookeeper://127.0.0.1:2181
    application:
      name: ${spring.application.name}
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    host: 127.0.0.1
    port: 7001
    timeout: 1000000
    database: 0
#    jedis:
#      pool:
#        max-idle: 5
#        max-active: 8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: postgres
    url: jdbc:postgresql://127.0.0.1:5432/taotao
    driver-class-name: org.postgresql.Driver
    dbcp2:
      max-wait-millis: 3000
      initial-size: 10
      max-idle: 5
logging:
  level:
#    java.sql: debug
#    org.apache.ibatis: debug
#    org.mybatis: debug
    com.smn.it.taotaomall.sso.dao: debug


