server:
  port: 8083
  servlet:
    context-path: /taotaomall/sso
spring:
  application:
    name: sso
  dubbo:
    server: true
    protocol:
      name: dubbo
      port: 20881
    registry:
      address: zookeeper://127.0.0.1:2181
    application:
      name: ${spring.application.name}
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003